export enum OrderType {
  KENDARAAN = 'KENDARAAN',
  TRAVEL_PACKAGE = 'TRAVEL_PACKAGE',
  AKOMODASI = 'AKOMODASI',
  DRIVER = 'DRIVER',
  GUIDER_TOUR = 'GUIDE_TOUR',
  AIRPORT_SHUTTLE = 'AIRPORT_SHUTTLE',
  PORT_SHUTTLE = 'PORT_SHUTTLE',
}
